project_id = "sysbtcikrbrrgafffody"

[functions.send-contact-email]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.import-hospitals]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false
