project_id = "sysbtcikrbrrgafffody"

[functions.send-contact-email]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.import-hospitals]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.find-missing-links]
verify_jwt = false

[functions.csrf-token]
verify_jwt = false

[functions.auth-cookie]
verify_jwt = false

[functions.logout]
verify_jwt = false

[functions.restore-session]
verify_jwt = false

[functions.import-texas-hospitals]
verify_jwt = false

[functions.remove-duplicates]
verify_jwt = false

[functions.fix-coordinates]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false